services:
  postgres:
    image: postgres:15-alpine
    container_name: database-unimatch

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: backend-unimatch

    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_TOKEN_KEY: ${JWT_TOKEN_KEY}
      SWAGGER_ENABLED: ${SWAGGER_ENABLED}

    ports:
      - "${APP_PORT}:8080"

    depends_on:
      - postgres

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-unimatch

    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-unimatch

    ports:
      - "127.0.0.1:3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"

    volumes:
      - grafana-storage:/var/lib/grafana

    depends_on:
      - prometheus

    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki-unimatch

    volumes:
      - ./src/main/resources/loki.yml:/etc/loki/loki.yml:ro
      - loki-data:/loki

    command:
      - '-config.file=/etc/loki/loki.yml'

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail-unimatch

    volumes:
      - ./src/main/resources/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

    command:
      - '-config.file=/etc/promtail/promtail.yml'

    restart: unless-stopped
    depends_on:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:
  grafana-storage:
  loki-data:
  prometheus-data:
