services:
  postgres:
    image: postgres:15-alpine
    container_name: database-unimatch

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: backend-unimatch

    environment:
      ACTIVE_PROFILE: ${ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_TOKEN_KEY: ${JWT_TOKEN_KEY}
      SWAGGER_ENABLED: ${SWAGGER_ENABLED}

    ports:
      - "${APP_PORT}:8080"

    depends_on:
      - postgres

    restart: unless-stopped

volumes:
  postgres_data:
