spring:
  application:
    name: unimatch

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN

  pattern:
    console: '{"timestamp":"%d{ISO8601}","level":"%p","service":"${spring.application.name:}","message":"%m","thread":"%thread","exception":"%wEx","className":"%logger{36}"}%n'

token:
  signing:
    key: ${JWT_TOKEN_KEY}

jwt:
  expiration:
    hours: 1

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-refresh-period: 60s
        timeout-duration: 5s
        register-health-indicator: true

    instances:
      authRegistration:
        base-config: default
        limit-for-period: 20

      authLogin:
        base-config: default
        limit-for-period: 60

      authVerifyEmail:
        base-config: default
        limit-for-period: 20

  circuitbreaker:
    configs:
        default:
          registerHealthIndicator: true
          slidingWindowSize: 10
          minimumNumberOfCalls: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 60000

    instances:
      database:
        base-config: default
        ignore-exceptions:
          - com.rar.unimatch.error.ResourceNotFoundException
          - com.rar.unimatch.error.BadRequestException

      auth:
        base-config: default
        ignore-exceptions:
          - com.rar.unimatch.error.ResourceNotFoundException
          - org.springframework.security.authentication.BadCredentialsException
          - com.rar.unimatch.error.BadRequestException

      minio:
        base-config: default
        ignore-exceptions:
          - com.rar.unimatch.error.ResourceNotFoundException
          - org.springframework.security.authentication.BadCredentialsException
          - com.rar.unimatch.error.BadRequestException

  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.sql.SQLException
          - org.springframework.dao.QueryTimeoutException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - io.minio.errors.MinioException
          - jakarta.mail.MessagingException

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

app:
  base-url: ${BASE_URL}

minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_USERNAME}
  secret-key: ${MINIO_PASSWORD}
  bucket: unimatch-images
