spring:
  application:
    name: unimatch

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

logging:
  level:
    root: INFO
    com.rar: DEBUG
    org.springframework.web: WARN
    org.hibernate: WARN

  pattern:
    console: '{"timestamp":"%d{ISO8601}","level":"%p","service":"${spring.application.name:}","traceId":"%X{traceId:-}","spanId":"%X{spanId:-}","parentId":"%X{parentId:-}","message":"%m","thread":"%thread","exception":"%wEx","className":"%logger{36}"}%n'


token:
  signing:
    key: ${JWT_TOKEN_KEY}

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-refresh-period: 60s
        timeout-duration: 5s
        register-health-indicator: true

    instances:
      authRegistration:
        base-config: default
        limit-for-period: 20

      authLogin:
        base-config: default
        limit-for-period: 60

  circuitbreaker:
    instances:
      database:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 60000
        ignore-exceptions:
          - com.rar.unimatch.error.ResourceNotFoundException
          - org.springframework.security.authentication.BadCredentialsException
          - com.rar.unimatch.error.BadRequestException

  retry:
    instances:
      database:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.sql.SQLException
          - org.springframework.dao.QueryTimeoutException
          - java.net.ConnectException
          - java.net.SocketTimeoutException

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
